name: Build and check PR

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    name: Build PR for LEGUI
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - uses: actions/checkout@v3

      # PREPARE AND BUILD
      - name: Set up JDK
        uses: actions/setup-java@v3.12.0
        with:
          java-version: 16
          distribution: 'temurin'
          cache: 'gradle'

      - name: Build with Gradle
        run: ./gradlew build

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test

      # SONAR CHECK
      - name: Run sonarqube check
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          sonarLogin: ${{secrets.sonarToken}}
          JAVA_OPTS: -Xmx3072m -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=128m
          GRADLE_OPTS: -Xmx3800m -XX:ReservedCodeCacheSize=128m -Dorg.gradle.daemon=false
        run: ./gradlew sonarqube

      # RUN TESTS
      - name: Run tests
        run: ./gradlew test
